name: Actions workflow

on: [push]

jobs:
  run-existing-action:
    runs-on: ubuntu-latest
    steps:
      - name: Use hello world action
        id: losGreet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Nunya Bidness
      - name: Console log greeting time
        run: echo "${{ steps.losGreet.outputs.time }}"
  checkout-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest master
        uses: actions/checkout@v2.3.4
      - name: Then list out the current directory
        run: |
          pwd
          ls -a